services:
  parser:
    container_name: parser-microservice
    image: chetminez/ru-marketplace-parser
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file:
      - .env.prod
    restart: always
    shm_size: 2GB
